# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_type_id',
            field=models.IntegerField(choices=[(1, 'Python'), (2, 'Django'), (3, 'Linux'), (4, 'GoLango'), (5, '数据分析'), (6, '机器学习')], default=None),
        ),
    ]
