# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20171001_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='site',
            field=models.CharField(max_length=32, unique=True, verbose_name='个人博客后缀'),
        ),
    ]
