# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20171001_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(upload_to='', verbose_name='头像'),
        ),
    ]
