# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20171003_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(upload_to='static/imgs', verbose_name='头像'),
        ),
    ]
